### GENERAL SETTINGS ###

# Site settings
title: Shotcut
description: "Shotcut is a free, open source, cross-platform video editor for Windows, Mac and Linux"
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "https://www.shotcut.org"
timezone: "America/Los_Angeles"

gems: ["jekyll-paginate"]
paginate: 5
paginate_path: "/blog/page:num/"

# Build settings
markdown: kramdown
permalink: /blog/:title/
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#115c77" # main theme color
  primary_rgb: "17,92,119" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#000" # body text and footer background
  background: "#fff"
  alternatebg: "#ddd"
  accent: "#c80000"
  link: "#115c77"
  link_hover: "#c80000"
  footer_heading: "#fff"
  footer_content: "#ddd"
  
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: facebook
    url: https://www.facebook.com/shotcutapp/
  - title: twitter
    url: https://twitter.com/shotcutapp
    
# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines: 
    - Adress,
    - City, State, Zip
    - United States
email: dan@dennedy.org
tel: (000) 000-0000


### GENERAL DATA FOR VARIOUS LOCATIONS ###
    
# Members information. Shown on About page.
members:
  - name: Dan Dennedy
    position: Lead Developer
    text: Bio or Description Here
    img: team01.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle
    
# Clients information. Shown on Home and About pages.
clients:
  - name: dribbble
    img: client01.png
  - name: Code is Poetry
    img: client02.png
  - name: Vimeo
    img: client03.png
  - name: VimeoPro
    img: client04.png
    
# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Shotcut is a free, open source, cross-platform video editor for Windows, Mac and Linux. Major features include support for a wide range of formats; no import required meaning native timeline editing; Blackmagic Design support for input and preview monitoring; and resolution support to 4k."
